name: Add ID to JSON

on:
  workflow_dispatch:
    inputs:
      newID:
        description: new ID to add
        required: true
        type: string

jobs:
  add_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read JSON input
        id: read_json
        uses: actions/github-script@v4
        with:
          script: |
            let jsonContent = require("./ids.json");
            jsonContent.ids.push("${{ inputs.newID }}")
            console.log(`::set-output name=new_json::${JSON.toString(jsonContent)}`);

      - name: Create New JSON
        run: |
          # Get the JSON input from the previous step
          new_json='${{ steps.read_json.outputs.new_json }}'
          
          # Save the output CSS to the file
          echo -e "${new_json}" > ids.json

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ids.json
          git commit -m "updated JSON"
          git push
