name: Convert CSS

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Add ID to JSON"]
    types:
      - completed

jobs:
  convert_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read JSON input
        id: read_json
        uses: actions/github-script@v4
        with:
          script: |
            const jsonContent = require("./ids.json");
            const css = `${jsonContent.ids.map(e=>`${e.includes("icons")&&`[src^="https://cdn.discordapp.com/${e}"]`||`[style^="background-image: url(\\"https://cdn.discordapp.com/avatars/${e}"],[src^="https://cdn.discordapp.com/avatars/${e}"]`}`).join(",")}{padding:20px;background-size:contain;width:0;height:0;background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAALCAIAAADEEvsIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE8SURBVChTFZDdalRBEIS75+fMzJ6zqwFBCORKMImCFwaiBJIrn8OX8U18wZDdM3890z2O8FEUVXVV+PvPXxiMIAiNSiRK1ugQ/JBx2WMudQzQ94+/mIpMaqZ8obRDr4o711rT3nOG1vTnLz+4xFFTn4vL60RqVK1IjnQ5c56+6rvb70h5pkiR01nim27ZCU2FEk2vHlh5oTD6Cn37T9uAjqMeRzlBuVL0wfJHJ/rp4elg1er0uqDH7rAfnXp/sMdFHyy8C/Zqds8/X5y3a7DBa2eGM7J5fVqX1SlvcAv2tDklGsEgLtp6uwTrwuIOxjllFzBWjGFrWN9/e2AQZQAVs5TOZR6G2HsvpSZmAhR9c/u1Dx7IMhq1RHWfu9nlssd4LpQbN3396U6GKDUQuPdMFIWr9FpLTGmnVkX4H50R12gRbOLvAAAAAElFTkSuQmCC)}`
            console.log(`::set-output name=css_content::${css}`);

      - name: Convert CSS
        run: |
          # Get the JSON input from the previous step
          css_content='${{ steps.read_json.outputs.css_content }}'
          
          # Save the output CSS to the file
          echo -e "${css_content}" > style.css

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add style.css
          git commit -m "Convert json to CSS"
          git push
