name: Convert CSS

on:
  push:
    branches:
      - main

jobs:
  convert_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read JSON input
        id: read_json
        uses: actions/github-script@v4
        with:
          script: |
            const jsonContent = require('./ids.json');
            const css = `${jsonContent.ids.map(e=>`[href*=""${e}""],[src*=""${e}""]`).join(",")}{filter:blur(20px)!important;clip-path:circle(50%)}`
            console.log(`::set-output name=css_content::${css}`);

      - name: Convert CSS
        run: |
          # Get the JSON input from the previous step
          css_content="${{ steps.read_json.outputs.css_content }}"
          
          # Save the output CSS to the file
          echo -e "${css_content}" > style.css

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add style.css
          git commit -m "Convert json to CSS"
          git push
