name: Convert CSS

on:
  push:
    branches:
      - main

jobs:
  convert_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read JSON input
        id: read_json
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const jsonContent = fs.readFileSync('ids.json', 'utf8');
            console.log(`::set-output name=json_content::${jsonContent}`);

      - name: Convert CSS
        run: |
          input_json="${{ steps.read_json.outputs.json_content }}"

          if [ -z "$input_json" ]; then
            echo "Error: JSON input is empty."
            exit 1
          fi
    
          echo -n "" > converted_styles.css

          for id in $(echo "${input_json}" | jq -r '.ids[]'); do
            echo -e "[href*=\"${id}\"] {\n  /* Your CSS rules for ID ${id} */\n}\n" >> converted_styles.css
          done

          cat converted_styles.css

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add converted_styles.css
          git commit -m "Convert src attributes to href in CSS"
          git push
